import type { Category, Product } from "@/types/product";

export const CATEGORIES: Category[] = [
  { id: "1", slug: "accounts", name: "Аккаунты", iconName: "UserCircle2", productsCount: 4218, accentFrom: "#7C3AED", accentTo: "#3B82F6" },
  { id: "2", slug: "currency", name: "Игровая валюта", iconName: "Coins", productsCount: 6031, accentFrom: "#F59E0B", accentTo: "#EF4444" },
  { id: "3", slug: "boosting", name: "Буст и прокачка", iconName: "TrendingUp", productsCount: 1874, accentFrom: "#22D3EE", accentTo: "#3B82F6" },
  { id: "4", slug: "items", name: "Внутриигровые предметы", iconName: "Package", productsCount: 3320, accentFrom: "#A855F7", accentTo: "#EC4899" },
  { id: "5", slug: "topup", name: "Пополнение баланса", iconName: "Wallet", productsCount: 2109, accentFrom: "#10B981", accentTo: "#22D3EE" },
  { id: "6", slug: "keys", name: "Ключи и подписки", iconName: "KeyRound", productsCount: 1542, accentFrom: "#EF4444", accentTo: "#F59E0B" },
];

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "dota2-account-immortal",
    title: "Аккаунт Dota 2 — ранг Immortal, 4200 часов",
    description: "Полный доступ, привязка к почте включена, 38 иммортал-предметов.",
    imageUrl: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?q=80&w=800&auto=format&fit=crop",
    price: 8900,
    oldPrice: 11200,
    currency: "RUB",
    categorySlug: "accounts",
    categoryName: "Аккаунты",
    rating: 4.9,
    reviewsCount: 214,
    salesCount: 1032,
    inStock: true,
    badges: ["hit", "sale"],
    seller: { id: "s1", name: "ProGamer_Store", avatarUrl: null, rating: 4.9, isVerified: true },
  },
  {
    id: "p2",
    slug: "valorant-boost-radiant",
    title: "Буст рейтинга Valorant до Radiant",
    description: "Опытные бустеры, полная конфиденциальность, средний срок — 5 дней.",
    imageUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop",
    price: 4500,
    currency: "RUB",
    categorySlug: "boosting",
    categoryName: "Буст и прокачка",
    rating: 4.8,
    reviewsCount: 156,
    salesCount: 640,
    inStock: true,
    badges: ["new"],
    seller: { id: "s2", name: "EliteBoost", avatarUrl: null, rating: 4.8, isVerified: true },
  },
  {
    id: "p3",
    slug: "genshin-primogems-3000",
    title: "Genshin Impact — 3000 примогемов",
    description: "Официальное пополнение через UID, зачисление до 15 минут.",
    imageUrl: "https://images.unsplash.com/photo-1580327344181-c1163234e5a0?q=80&w=800&auto=format&fit=crop",
    price: 2450,
    currency: "RUB",
    categorySlug: "currency",
    categoryName: "Игровая валюта",
    rating: 5,
    reviewsCount: 892,
    salesCount: 3410,
    inStock: true,
    badges: ["hit"],
    seller: { id: "s3", name: "TopUp.Center", avatarUrl: null, rating: 4.95, isVerified: true },
  },
  {
    id: "p4",
    slug: "steam-key-cyberpunk",
    title: "Steam-ключ Cyberpunk 2077: Ultimate Edition",
    description: "Регион RU/CIS, активация в Steam, мгновенная доставка ключа.",
    imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=800&auto=format&fit=crop",
    price: 1990,
    oldPrice: 2990,
    currency: "RUB",
    categorySlug: "keys",
    categoryName: "Ключи и подписки",
    rating: 4.7,
    reviewsCount: 431,
    salesCount: 2050,
    inStock: true,
    badges: ["sale"],
    seller: { id: "s4", name: "KeyMarket", avatarUrl: null, rating: 4.7, isVerified: false },
  },
  {
    id: "p5",
    slug: "fortnite-account-rare-skins",
    title: "Аккаунт Fortnite с редкими скинами (32 шт.)",
    description: "Включает Renegade Raider, Black Knight, Galaxy. Полная смена данных.",
    imageUrl: "https://images.unsplash.com/photo-1580327332925-a10e6cb11baa?q=80&w=800&auto=format&fit=crop",
    price: 15400,
    currency: "RUB",
    categorySlug: "accounts",
    categoryName: "Аккаунты",
    rating: 4.85,
    reviewsCount: 98,
    salesCount: 211,
    inStock: true,
    badges: ["exclusive"],
    seller: { id: "s1", name: "ProGamer_Store", avatarUrl: null, rating: 4.9, isVerified: true },
  },
  {
    id: "p6",
    slug: "wow-gold-eu-100k",
    title: "World of Warcraft — 100 000 голды (EU)",
    description: "Быстрая передача через аукцион, все сервера EU.",
    imageUrl: "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?q=80&w=800&auto=format&fit=crop",
    price: 3200,
    currency: "RUB",
    categorySlug: "currency",
    categoryName: "Игровая валюта",
    rating: 4.6,
    reviewsCount: 302,
    salesCount: 1590,
    inStock: false,
    badges: [],
    seller: { id: "s5", name: "GoldRush", avatarUrl: null, rating: 4.6, isVerified: true },
  },
  {
    id: "p7",
    slug: "psn-plus-12-months",
    title: "PlayStation Plus Extra — подписка на 12 месяцев",
    description: "Активация через турецкий регион, подробная инструкция прилагается.",
    imageUrl: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?q=80&w=800&auto=format&fit=crop",
    price: 3990,
    oldPrice: 5200,
    currency: "RUB",
    categorySlug: "keys",
    categoryName: "Ключи и подписки",
    rating: 4.75,
    reviewsCount: 677,
    salesCount: 2870,
    inStock: true,
    badges: ["sale", "hit"],
    seller: { id: "s6", name: "PS.Store.RU", avatarUrl: null, rating: 4.8, isVerified: true },
  },
  {
    id: "p8",
    slug: "csgo-boost-faceit-lvl10",
    title: "Буст FACEIT до 10 уровня — CS2",
    description: "Игра от вашего лица или совместно, гарантия результата.",
    imageUrl: "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?q=80&w=800&auto=format&fit=crop",
    price: 6700,
    currency: "RUB",
    categorySlug: "boosting",
    categoryName: "Буст и прокачка",
    rating: 4.9,
    reviewsCount: 244,
    salesCount: 980,
    inStock: true,
    badges: ["new"],
    seller: { id: "s2", name: "EliteBoost", avatarUrl: null, rating: 4.8, isVerified: true },
  },
];

export const LIVE_DEALS = [
  { buyer: "Артём К.", product: "Buff-буст рейтинга Dota 2", price: "1 200 ₽", minutesAgo: 2 },
  { buyer: "Мария С.", product: "3000 примогемов Genshin Impact", price: "2 450 ₽", minutesAgo: 3 },
  { buyer: "Игорь П.", product: "Steam-ключ Cyberpunk 2077", price: "1 990 ₽", minutesAgo: 5 },
  { buyer: "Дарья В.", product: "Аккаунт Valorant Immortal", price: "7 300 ₽", minutesAgo: 6 },
  { buyer: "Никита Р.", product: "PS Plus Extra на 12 месяцев", price: "3 990 ₽", minutesAgo: 8 },
  { buyer: "Ольга Т.", product: "100 000 голды WoW EU", price: "3 200 ₽", minutesAgo: 9 },
  { buyer: "Сергей Л.", product: "Буст FACEIT до 10 уровня", price: "6 700 ₽", minutesAgo: 11 },
];
